Update vrw-encryption.md
ibm-cloud-docs/vmwaresolutions pull request #979
Opened 2022-01-25 16:22 UTC by sandeep-at-ibm

Document updated for:
- flow
- independent - no 3rd party use case

2022-01-25 16:27 UTC, sandeep-at-ibm commented
Picture for Fig1:
<img width="984" alt="vrw-hpcs-mgmt-no-3rd-party" src="https://user-images.githubusercontent.com/61752731/151017541-ec521c4b-d426-4e14-abae-769a0961ad77.png">

Please have Scott Moonen review this doc for accuracy

2022-01-28 20:10 UTC, delia-rusu commented
Under review with Scott and Joseph.

2022-02-01 16:01 UTC, pokeyjo submitted a review, later dismissed

2022-02-01 19:11 UTC, delia-rusu commented
@sandeep-at-ibm thank you! Can you please provide the image in SVG format? PNG is not supported per translation requirements.

2022-02-01 20:04 UTC, smoonen requested changes

2022-02-01 20:04 UTC, smoonen commented on archiref/vrw/vrw-encryption.md
> +{{site.data.keyword.cloud_notm}} for VMware® Regulated Workloads relies upon VMware vSphere® encryption to secure management and production VMs while at-rest or in-transit. VMware vSphere® encryption
I think it would be good to keep the statement "HPCS is a mandatory service."

2022-02-01 20:04 UTC, smoonen commented on archiref/vrw/vrw-encryption.md
> +![vSphere encryption with Hyper Protect Crypto Services](../../images/vrw-hpcs-mgmt-no-3rd-party.png){: caption="Figure 1. vSphere encryption with Hyper Protect Crypto Services - no third parties" ca
This figure hasn't been checked into the branch yet so it doesn't resolve.

Also, IBM Cloud docs standards require the use of SVG so that all text within the image can be translated. Could you generate this as an SVG rather than a PNG? Thanks!

2022-02-01 20:07 UTC, sandeep-at-ibm commented on archiref/vrw/vrw-encryption.md
> +{{site.data.keyword.cloud_notm}} for VMware® Regulated Workloads relies upon VMware vSphere® encryption to secure management and production VMs while at-rest or in-transit. VMware vSphere® encryption
agree @smoonen

2022-02-02 02:45 UTC, sandeep-at-ibm commented on archiref/vrw/vrw-encryption.md
> +![vSphere encryption with Hyper Protect Crypto Services](../../images/vrw-hpcs-mgmt-no-3rd-party.png){: caption="Figure 1. vSphere encryption with Hyper Protect Crypto Services - no third parties" ca
uploaded file to `images/vmware-vsphere-encryption.drawio.svg`

2022-02-02 02:46 UTC, sandeep-at-ibm commented
@smoonen @delia-rusu uploaded the image in SVG format.
Please check

2022-02-04 16:47 UTC, delia-rusu commented
Published on the test server, please review and reopen if any updates are needed: https://test.cloud.ibm.com/docs/vmwaresolutions?topic=vmwaresolutions-vrw-encryption

2022-02-04 16:47 UTC, closed without merging